### ISSUE TITLE
ripper does not allow to generate WebAPI token

### ISSUE THREAD

**Issue by s-leon** [SolidHal/spotify-ripper#12]
I just installed Spotify Ripper on Arch with Kernel 4.10.10 and tried authorizing the WebAPI.
I have a premium account and created the dummy App.
I stored the ID and Secret as enviroment var's and in "/usr/lib/python2.7/site-packages/spotify_ripper/remove_all_from_playlist.py". (printenv shows correctly)
Now for the problem:
as described in the readme i launched spotify-ripper with -r set
the output is as follows:
```
[user@arch Downloads]$ spotify-ripper -r -u user -p pass spotify:track:0eGsygTp906u18L0Oimnem
--REMOVE-FROM-PLAYLIST WARNING:
SPOTIFY HAS BROKEN libspotify
THE PLAYLIST WILL BE EMPTIED AT THE END USING THE WEB API
CHECK THE GITHUB FOR INSTRUCTIONS ON AUTHENTICATING THE WEB API
Spotify Ripper - v2.11
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
  Output directory:	/home/user/Downloads
  Settings directory:	/home/user/.spotify-ripper
  Format String:	{album_artist}/{album}/{artist} - {track_name}.{ext}
  Overwrite files:	No

Please copy your spotify_appkey.key to /home/user/.spotify-ripper, or use the --key|-k option

```

python versions are: python2.7.13 / python3.6.0
python2-pyspotify:  2.0.5-2
python2-spotipy:  2.4.3-1

I assume that using the WebAPI i wont need the deprecated libspotify key? 
Can i manually generate the WebAPI Token?

**Comment by wessel145** [comment]
I got the same problem, can't get the link to authenticate the web api.
Maybe it's because you need a libspotify key in the first place, i don't hope so.

**Comment by wessel145** [comment]
I actually managed to get a Web Api token (.cache-#username#). by changing the code in the remove_all_from_playlist.py file to `token = util.prompt_for_user_token(username, scope, client_id='#ClientID#', client_secret='#ClientSecret', redirect_uri='http://www.purple.com')`  

So it puts out a .cache-#username# file, but still no fix to the problem, maybe this will help you

**Comment by SolidHal** [comment]
See https://github.com/SolidHal/spotify-ripper/issues/13
