### ISSUE TITLE
Who is purple.com ?

### ISSUE THREAD

**Issue by EmptyStackExn** [SolidHal/spotify-ripper#14]

**Comment by SolidHal** [comment]
Just a random site that I use to have the spotify key generated, you can (theoretically) use any functioning url

**Comment by granvillepaut** [comment]
this is a funny hack :p

**Comment by SolidHal** [comment]
@granvillepaut Yep! Thats all my fork of spotify ripper was meant to be, a hack to get it working in a minimal fashion. Lots of things in here I wouldn't suggest doing for a production environment hahaha
