### ISSUE TITLE
large-cover-art no longer works

### ISSUE THREAD

**Issue by ImaginaryCs** [SolidHal/spotify-ripper#15]
large-cover-art no longer works,
the cover art is always in 300x300.
It used to work, so I suspect it has something to do with the web api policy change on 5/29.

Now I always get
"URL returned non-200 HTTP code: 401" 
after
"Attempting to retrieve tracks from Spotify's Web API"
I suspect this is related to the cover art issue.

I have generated Web API tokens,
but how do I add them to make things work?

**Comment by ImaginaryCs** [comment]
I realized "remove all from playlist"  uses Spotipy, which can access the Web API correctly.
So I suppose it would work if also get meta tags and cover art by Spotipy.

Thanks.

**Comment by SolidHal** [comment]
Closing this issue as this is no longer under active development, reference my comment on: #23
