### ISSUE TITLE
Can you rip playlists with more than 100 songs?

### ISSUE THREAD

**Issue by gianpaj** [SolidHal/spotify-ripper#16]
I'm having an issue downloading more than 100 songs.

For example, when running this command:
```
spotify-ripper -l spotify:user:USERNAME:playlist:612354abbc....
```

And you add a `len()`, it returns 100 songs:

```python
track_list = playlist['tracks'].get('items')
```

https://github.com/SolidHal/spotify-ripper/blob/master/spotify_ripper/ripper.py#L433

I'll continue debugging, but if somebody knows if there's a limitation of the API or of any libs this program depends on that would be great

**Comment by gianpaj** [comment]
It's an actual limitation of the Spotify Web API 😢 
https://developer.spotify.com/web-api/get-playlists-tracks/

**Comment by tinuva** [comment]
If you still need to test against a playlist of 100+ tracks, give the following fork/branch a try: https://github.com/tinuva/spotify-ripper/tree/apiPlaylistFixes
