### ISSUE TITLE
Is Art cover embedded working for anybody ?

### ISSUE THREAD

**Issue by Pancho111** [SolidHal/spotify-ripper#34]
Hi , Art Cover embedded stopped working on my end ?
Can anybody please confirm if it is working now?
Thanks

**Comment by tom-schaek** [comment]
This stopped working for me a couple of weeks ago. Bummer. Would love to get this working again. If i use --cover-file test.jpg parameter, the test.jpg gets written but it's empty.

**Comment by Pancho111** [comment]
That is correct it is empty , the cover is not downloading anymore.
