### ISSUE TITLE
Any way to install this on Windows 10 Bash Shell?

### ISSUE THREAD

**Issue by jonaaa20** [SolidHal/spotify-ripper#8]

**Comment by roushik** [comment]
First install the prerequisites
"sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
xz-utils tk-dev"

Then install pyenv 
"curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash"

Restart the terminal and Install your desired python version
"pyenv install 2.7.13"

Set it as global
"pyenv global 2.7.13"

Verify the version
"python -V "

After that, follow the "To install spotify-ripper once pyenv is setup" section  in Readme
